#! /bin/bash

CONTAINER_NAME="lardi-grafana-dashboard"
if [ $(docker ps -a | grep $CONTAINER_NAME | awk '{print $NF}' | wc -l) -gt 0 ];then
	docker kill $CONTAINER_NAME
	docker rm $CONTAINER_NAME
fi
if [ -d "./logs" ];then
	rm -fr ./logs/*
fi

docker run -d -v $(pwd)/logs:/var/log/supervisor -p 80:80 -p 81:81 -p 2003:2003 --name $CONTAINER_NAME lardi/grafana_graphite
